ALTER TABLE  `#__hotelreservation_excursions` ADD  `currency_id` INT( 2 ) NOT NULL DEFAULT '0' ;
ALTER TABLE  `#__hotelreservation_excursions` ADD  `age_restrictions_required` INT( 1 ) NOT NULL DEFAULT '0' ;
ALTER TABLE  `#__hotelreservation_excursions` ADD  `age_restrictions_min` tinyint( 3 ) NOT NULL DEFAULT '0' ;
ALTER TABLE  `#__hotelreservation_excursions` ADD  `age_restrictions_max` tinyint( 3 ) NOT NULL DEFAULT '0' ;

ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_2` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_3` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_4` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_5` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_6` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_7` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_8` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_9` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_10` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_11` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_12` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_13` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_14` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_15` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_16` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_17` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_18` decimal(12,2) NOT NULL DEFAULT '0';
ALTER TABLE  `#__hotelreservation_excursion_rate_prices` ADD   `price_19` decimal(12,2) NOT NULL DEFAULT '0';
