
DROP TABLE IF EXISTS `qk7ce_template_styles`;
CREATE TABLE `qk7ce_template_styles` (
  `id` int(10) UNSIGNED NOT NULL,
  `template` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `client_id` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `home` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `params` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `qk7ce_template_styles` VALUES(4, 'beez3', 0, '0', 'Beez3 - Default', '{\"wrapperSmall\":\"53\",\"wrapperLarge\":\"72\",\"logo\":\"images\\/joomla_black.gif\",\"sitetitle\":\"Joomla!\",\"sitedescription\":\"Open Source Content Management\",\"navposition\":\"left\",\"templatecolor\":\"personal\",\"html5\":\"0\"}');
INSERT INTO `qk7ce_template_styles` VALUES(5, 'hathor', 1, '0', 'Hathor - Default', '{\"showSiteName\":\"0\",\"colourChoice\":\"\",\"boldText\":\"0\"}');
INSERT INTO `qk7ce_template_styles` VALUES(7, 'protostar', 0, '0', 'protostar - Default', '{\"templateColor\":\"\",\"logoFile\":\"\",\"googleFont\":\"1\",\"googleFontName\":\"Open+Sans\",\"fluidContainer\":\"0\"}');
INSERT INTO `qk7ce_template_styles` VALUES(8, 'isis', 1, '1', 'isis - Default', '{\"templateColor\":\"\",\"logoFile\":\"\"}');
INSERT INTO `qk7ce_template_styles` VALUES(9, 'theme3461', 0, '1', 'theme3461 - Default', '{\"top_layout\":\"normal\",\"header_layout\":\"normal\",\"navigation_layout\":\"normal\",\"showcase_layout\":\"normal\",\"feature_layout\":\"normal\",\"breadcrumbs_layout\":\"normal\",\"maintop_layout\":\"normal\",\"map_layout\":\"normal\",\"content_layout\":\"normal\",\"video_layout\":\"normal\",\"mainbottom_layout\":\"fullwidth\",\"mainbottom-2_layout\":\"normal\",\"mainbottom-3_layout\":\"normal\",\"mainbottom-4_layout\":\"normal\",\"mainbottom-5_layout\":\"normal\",\"bottom_layout\":\"normal\",\"footer_layout\":\"normal\",\"copyright_layout\":\"normal\",\"logoFile\":\"\",\"logoBlockWidth\":\"4\",\"LogoDescription\":\"1\",\"logo_description_title\":\"online marketing\",\"footerLogo\":\"0\",\"footerLogoFile\":\"\",\"footerWidth\":\"6\",\"footerCopy\":\"1\",\"footerText\":\"1\",\"footerYear\":\"1\",\"privacyLink\":\"1\",\"privacy_link_menu\":\"176\",\"privacy_link_title\":\"Ochrana soukromí\",\"termsLink\":\"1\",\"terms_link_menu\":\"176\",\"terms_link_title\":\"Podmínky užití\",\"asideLeftWidth\":\"4\",\"asideRightWidth\":\"3\",\"featuredPageHeading\":\"h2\",\"featuredItemHeading\":\"h5\",\"categoryPageHeading\":\"h2\",\"categoryItemHeading\":\"h5\",\"blogPageHeading\":\"h2\",\"blogItemHeading\":\"h5\",\"itemItemHeading\":\"h2\",\"itemBlogItemHeading\":\"h5\",\"totop\":\"1\",\"totop_text\":\" \",\"todesktop\":\"0\",\"todesktop_text\":\"Back to desktop version\",\"tomobile_text\":\"Back to mobile version\",\"blackandwhite\":\"0\",\"invertHoverEffect\":\"1\",\"fadeIn\":\"500\",\"fadeOut\":\"500\",\"countdown_time\":\"\",\"color_scheme\":\"color_scheme_1\"}');
INSERT INTO `qk7ce_template_styles` VALUES(10, 'theme3461', 0, '0', 'theme3461 - Careers', '{\"top_layout\":\"normal\",\"header_layout\":\"normal\",\"navigation_layout\":\"normal\",\"showcase_layout\":\"normal\",\"feature_layout\":\"normal\",\"breadcrumbs_layout\":\"normal\",\"maintop_layout\":\"normal\",\"map_layout\":\"normal\",\"content_layout\":\"normal\",\"video_layout\":\"normal\",\"mainbottom_layout\":\"fullwidth\",\"mainbottom-2_layout\":\"normal\",\"mainbottom-3_layout\":\"normal\",\"mainbottom-4_layout\":\"normal\",\"mainbottom-5_layout\":\"normal\",\"bottom_layout\":\"normal\",\"footer_layout\":\"normal\",\"copyright_layout\":\"normal\",\"logoFile\":\"\",\"logoBlockWidth\":\"4\",\"LogoDescription\":\"1\",\"logo_description_title\":\"online marketing\",\"footerLogo\":\"0\",\"footerLogoFile\":\"\",\"footerWidth\":\"6\",\"footerCopy\":\"1\",\"footerText\":\"1\",\"footerYear\":\"1\",\"privacyLink\":\"1\",\"privacy_link_menu\":\"176\",\"privacy_link_title\":\"Ochrana soukromí\",\"termsLink\":\"1\",\"terms_link_menu\":\"176\",\"terms_link_title\":\"Podmínky užití\",\"asideLeftWidth\":\"4\",\"asideRightWidth\":\"5\",\"featuredPageHeading\":\"h2\",\"featuredItemHeading\":\"h5\",\"categoryPageHeading\":\"h2\",\"categoryItemHeading\":\"h5\",\"blogPageHeading\":\"h2\",\"blogItemHeading\":\"h5\",\"itemItemHeading\":\"h2\",\"itemBlogItemHeading\":\"h5\",\"totop\":\"1\",\"totop_text\":\" \",\"todesktop\":\"0\",\"todesktop_text\":\"Back to desktop version\",\"tomobile_text\":\"Back to mobile version\",\"blackandwhite\":\"0\",\"invertHoverEffect\":\"1\",\"fadeIn\":\"500\",\"fadeOut\":\"500\",\"countdown_time\":\"\",\"color_scheme\":\"color_scheme_1\"}');
INSERT INTO `qk7ce_template_styles` VALUES(11, 'theme3461', 0, '0', 'theme3461 - Home', '{\"top_layout\":\"normal\",\"header_layout\":\"normal\",\"navigation_layout\":\"normal\",\"showcase_layout\":\"normal\",\"feature_layout\":\"normal\",\"breadcrumbs_layout\":\"normal\",\"maintop_layout\":\"fullwidth\",\"map_layout\":\"normal\",\"content_layout\":\"normal\",\"video_layout\":\"normal\",\"mainbottom_layout\":\"fullwidth\",\"mainbottom-2_layout\":\"normal\",\"mainbottom-3_layout\":\"normal\",\"mainbottom-4_layout\":\"normal\",\"mainbottom-5_layout\":\"normal\",\"bottom_layout\":\"normal\",\"footer_layout\":\"normal\",\"copyright_layout\":\"normal\",\"logoFile\":\"\",\"logoBlockWidth\":\"4\",\"LogoDescription\":\"1\",\"logo_description_title\":\"online marketing\",\"footerLogo\":\"0\",\"footerLogoFile\":\"\",\"footerWidth\":\"6\",\"footerCopy\":\"1\",\"footerText\":\"1\",\"footerYear\":\"1\",\"privacyLink\":\"1\",\"privacy_link_menu\":\"176\",\"privacy_link_title\":\"Ochrana soukromí\",\"termsLink\":\"1\",\"terms_link_menu\":\"176\",\"terms_link_title\":\"Podmínky užití\",\"asideLeftWidth\":\"4\",\"asideRightWidth\":\"3\",\"featuredPageHeading\":\"h2\",\"featuredItemHeading\":\"h5\",\"categoryPageHeading\":\"h2\",\"categoryItemHeading\":\"h5\",\"blogPageHeading\":\"h2\",\"blogItemHeading\":\"h5\",\"itemItemHeading\":\"h2\",\"itemBlogItemHeading\":\"h5\",\"totop\":\"1\",\"totop_text\":\"\",\"todesktop\":\"0\",\"todesktop_text\":\"Back to desktop version\",\"tomobile_text\":\"Back to mobile version\",\"blackandwhite\":\"0\",\"invertHoverEffect\":\"1\",\"fadeIn\":\"500\",\"fadeOut\":\"500\",\"countdown_time\":\"\",\"color_scheme\":\"color_scheme_1\"}');
