
DROP TABLE IF EXISTS `qk7ce_kunena_messages_text`;
CREATE TABLE `qk7ce_kunena_messages_text` (
  `mesid` int(11) NOT NULL DEFAULT '0',
  `message` mediumtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `qk7ce_kunena_messages_text` VALUES(1, 'Thank you for choosing Kunena for your community forum needs in Joomla. \r\n Kunena, translated from Swahili meaning “to speak”, is built by a team of open source professionals with the goal of providing a top quality, tightly unified forum solution for Joomla. \r\nAdditional Kunena Resources\r\nKunena Documentation: [url]http://www.kunena.org/docs[/url] \r\nKunena Support Forum: [url]http://www.kunena.org/forum[/url] \r\nKunena Downloads: [url]http://www.kunena.org/download[/url] \r\nKunena Blog: [url]http://www.kunena.org/blog[/url] \r\nFollow Kunena on Twitter: [url]http://www.kunena.org/twitter[/url]');
INSERT INTO `qk7ce_kunena_messages_text` VALUES(2, 'Kunena is the ideal forum extension for Joomla. It\'s free, fully integrated, and no bridges or hacks are required.\r\n\r\nWant to know more about the Kunena Project? See how the open source philosophy drives our community, follow our development on GitHub, and how you can participate to make Kunena even better.');
INSERT INTO `qk7ce_kunena_messages_text` VALUES(3, 'This is a community-driven self-help category to ask questions about designing or developing your own Kunena template. Please be aware that there are rules that apply to topics posted in this category:\r\n\r\n[b]Do not use this category for:[/b]\r\nasking questions about how to make simple changes to a template designed by the Kunena project team (use K 3.0 Templates instead);\r\nadvertising your own template designs.\r\n\r\nTopics that do not meet the above guidelines may be removed without notice.');
INSERT INTO `qk7ce_kunena_messages_text` VALUES(4, 'Hello mates. Can i setup Kunena Forum so that some user\'s notes (but not all) will be availible for other users and some not by their wish? The main idea is to create personalized diary of the users and functionality of Kunena Forum seems to be most suitable for this.');
INSERT INTO `qk7ce_kunena_messages_text` VALUES(5, 'Hi.\r\n\r\nI\'m looking to have 1 template for 1 categorie and an other template for all others catégories.\r\nSomeone he already well-considered the problem ?\r\n\r\nRegards.');
INSERT INTO `qk7ce_kunena_messages_text` VALUES(6, 'Sed justo felis, lacinia at scelerisque a, semper et ante. Fusce posuere lacus eu mi lacinia et fringilla elit sollicitudin. Maecenas non odio nunc. In ut sollicitudin magna. Sed sit amet tincidunt odio. Mauris pharetra adipiscing urna ut accumsan. Suspendisse nec risus in felis fermentum blandit.\r\n\r\nNam nec lectus ut orci porta volutpat id at purus. Sed sagittis congue dapibus. Proin dolor metus, pharetra ut pulvinar nec, condimentum quis libero. Sed fermentum tortor ac elit tristique vel dapibus sem porta. Suspendisse aliquet posuere ultrices. Proin facilisis libero lacinia erat pretium faucibus. In tortor nunc, posuere eget commodo et, eleifend vel risus.');
INSERT INTO `qk7ce_kunena_messages_text` VALUES(7, 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam erat volutpat. Pellentesque non libero dui, vitae pharetra urna. Vestibulum accumsan pulvinar magna sed consectetur. Nulla congue condimentum aliquam. Donec non libero lectus, id mollis nisi. Morbi turpis magna, varius in ullamcorper nec, suscipit sagittis nibh. Nam elementum aliquam turpis eget egestas. Cras ligula nisi, interdum et vulputate nec, sagittis a tellus. In hac habitasse platea dictumst. In in sem libero. Fusce cursus, metus eu commodo hendrerit, arcu nibh consequat lectus, nec suscipit eros urna in ipsum. Praesent et enim a nisl commodo sodales non id neque. Ut sodales dignissim massa vitae hendrerit. Sed porttitor purus ut ante fermentum quis mollis velit pellentesque.\r\n\r\nEtiam nisi felis, fermentum vitae ultrices non, euismod in magna. In mattis velit ut eros tristique a congue erat consequat. Suspendisse consequat, justo eu gravida semper, ligula turpis dignissim dolor, vitae lacinia velit metus id libero. Nullam consectetur rhoncus magna, quis pharetra tortor bibendum quis. Curabitur ac ante nisl. Nullam mauris arcu, malesuada eu consectetur non, eleifend quis est. Nullam dictum, leo vulputate elementum porttitor, enim mi posuere augue, id porttitor leo sapien sed libero. Quisque est velit, aliquam bibendum vestibulum eget, tristique a odio.');
