
DROP TABLE IF EXISTS `qk7ce_tz_portfolio_plus_extensions`;
CREATE TABLE `qk7ce_tz_portfolio_plus_extensions` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `type` varchar(100) NOT NULL,
  `element` varchar(100) NOT NULL,
  `folder` varchar(100) NOT NULL,
  `protected` tinyint(3) NOT NULL,
  `manifest_cache` text NOT NULL,
  `params` text NOT NULL,
  `checked_out` int(10) UNSIGNED NOT NULL,
  `checked_out_time` datetime NOT NULL,
  `published` tinyint(4) NOT NULL,
  `access` int(10) NOT NULL,
  `ordering` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `qk7ce_tz_portfolio_plus_extensions` VALUES(1, 'system', 'tz_portfolio_plus-template', 'system', '', 1, '{\"name\":\"system\",\"type\":\"tz_portfolio_plus-template\",\"creationDate\":\"July 17th 2015\",\"author\":\"DuongTVTemplaza\",\"copyright\":\"Copyright (C) 2015 TemPlaza. All rights reserved.\",\"authorEmail\":\"info@templaza.com\",\"authorUrl\":\"\",\"version\":\"1.0\",\"description\":\"TZ_PORTFOLIO_PLUS_TPL_XML_DESCRIPTION\",\"group\":\"\",\"filename\":\"template\"}', '', 0, '0000-00-00 00:00:00', 1, 1, 0);
INSERT INTO `qk7ce_tz_portfolio_plus_extensions` VALUES(2, 'plg_content_vote', 'tz_portfolio_plus-plugin', 'vote', 'content', 1, '{\"name\":\"plg_content_vote\",\"type\":\"tz_portfolio_plus-plugin\",\"creationDate\":\"Aug, 09th 2012\",\"author\":\"DuongTVTemPlaza\",\"copyright\":\"Copyright (C) 2015 Open Source Matters. All rights reserved.\",\"authorEmail\":\"support@templaza.com\",\"authorUrl\":\"www.templaza.com\",\"version\":\"1.0.7\",\"description\":\"PLG_CONTENT_VOTE_XML_DESCRIPTION\",\"group\":\"\",\"filename\":\"vote\"}', '{\"show_cat_vote\":\"0\",\"show_cat_counter\":\"1\",\"cat_unrated\":\"1\",\"show_counter\":\"1\",\"unrated\":\"1\"}', 0, '2016-01-07 10:03:01', 1, 1, 0);
INSERT INTO `qk7ce_tz_portfolio_plus_extensions` VALUES(3, 'plg_mediatype_image', 'tz_portfolio_plus-plugin', 'image', 'mediatype', 1, '{\"name\":\"plg_mediatype_image\",\"type\":\"tz_portfolio_plus-plugin\",\"creationDate\":\"September 5th 2017\",\"author\":\"DuongTVTemPlaza\",\"copyright\":\"Copyright (C) 2017 TemPlaza. All rights reserved.\",\"authorEmail\":\"support@templaza.com\",\"authorUrl\":\"www.templaza.com\\/\",\"version\":\"1.0.8\",\"description\":\"PLG_MEDIATYPE_IMAGE_XML_DESCRIPTION\",\"group\":\"\",\"filename\":\"image\"}', '{\"image_file_size\":\"10\",\"image_file_type\":\"bmp,gif,jpg,jpeg,png,BMP,GIF,JPG,JPEG,PNG\",\"image_mime_type\":\"image\\/jpeg,image\\/gif,image\\/png,image\\/bmp\",\"image_size\":[\"{\\\"title\\\":\\\"XSmall\\\",\\\"width\\\":\\\"100\\\",\\\"image_name_prefix\\\":\\\"xs\\\"}\",\"{\\\"title\\\":\\\"Small\\\",\\\"width\\\":\\\"200\\\",\\\"image_name_prefix\\\":\\\"s\\\"}\",\"{\\\"title\\\":\\\"Medium\\\",\\\"width\\\":\\\"400\\\",\\\"image_name_prefix\\\":\\\"m\\\"}\",\"{\\\"title\\\":\\\"Large\\\",\\\"width\\\":\\\"600\\\",\\\"image_name_prefix\\\":\\\"l\\\"}\",\"{\\\"title\\\":\\\"XLarge\\\",\\\"width\\\":\\\"900\\\",\\\"image_name_prefix\\\":\\\"xl\\\"}\"],\"mt_image_show_feed_image\":\"1\",\"mt_image_feed_size\":\"o\",\"mt_show_cat_image_hover\":\"1\",\"mt_cat_image_size\":\"o\",\"mt_image_size\":\"o\",\"mt_show_image_hover\":\"1\",\"mt_image_use_cloud\":\"0\",\"mt_image_related_show_image\":\"1\",\"mt_image_related_size\":\"o\",\"mt_image_cloud_size\":\"o\",\"mt_image_cloud_position\":\"inside\",\"mt_image_cloud_softfocus\":\"0\",\"mt_image_cloud_show_title\":\"1\",\"mt_image_cloud_width\":\"\",\"mt_image_cloud_height\":\"\",\"mt_image_cloud_adjustX\":\"0\",\"mt_image_cloud_adjustY\":\"0\",\"mt_image_cloud_tint\":\"\",\"mt_image_cloud_tint_opacity\":\"0.5\",\"mt_image_cloud_len_opacity\":\"0.5\",\"mt_image_cloud_smoothmove\":\"3\",\"mt_image_cloud_title_opacity\":\"0.5\"}', 0, '0000-00-00 00:00:00', 1, 1, 0);
INSERT INTO `qk7ce_tz_portfolio_plus_extensions` VALUES(4, 'plg_extrafields_text', 'tz_portfolio_plus-plugin', 'text', 'extrafields', 1, '{\"name\":\"plg_extrafields_text\",\"type\":\"tz_portfolio_plus-plugin\",\"creationDate\":\"October 20th 2015\",\"author\":\"DuongTVTemPlaza\",\"copyright\":\"Copyright (C) 2015 TemPlaza. All rights reserved.\",\"authorEmail\":\"support@templaza.com\",\"authorUrl\":\"www.templaza.com\\/\",\"version\":\"1.0.7\",\"description\":\"PLG_EXTRAFIELDS_TEXT_XML_DESCRIPTION\",\"group\":\"\",\"filename\":\"text\"}', '{\"suggestion\":\"0\"}', 0, '0000-00-00 00:00:00', 1, 1, 0);
INSERT INTO `qk7ce_tz_portfolio_plus_extensions` VALUES(5, 'plg_extrafields_textarea', 'tz_portfolio_plus-plugin', 'textarea', 'extrafields', 1, '{\"name\":\"plg_extrafields_textarea\",\"type\":\"tz_portfolio_plus-plugin\",\"creationDate\":\"October 20th 2015\",\"author\":\"DuongTVTemPlaza\",\"copyright\":\"Copyright (C) 2015 TemPlaza. All rights reserved.\",\"authorEmail\":\"support@templaza.com\",\"authorUrl\":\"www.templaza.com\\/\",\"version\":\"1.0.7\",\"description\":\"PLG_EXTRAFIELDS_TEXTAREA_XML_DESCRIPTION\",\"group\":\"\",\"filename\":\"textarea\"}', '{\"cols\":\"50\",\"rows\":\"5\",\"use_editor_back_end\":\"0\",\"use_editor_front_end\":\"0\",\"groups_can_use_frontend_editor\":\"1\"}', 0, '0000-00-00 00:00:00', 1, 1, 0);
INSERT INTO `qk7ce_tz_portfolio_plus_extensions` VALUES(6, 'plg_extrafields_checkboxes', 'tz_portfolio_plus-plugin', 'checkboxes', 'extrafields', 1, '{\"name\":\"plg_extrafields_checkboxes\",\"type\":\"tz_portfolio_plus-plugin\",\"creationDate\":\"October 20th 2015\",\"author\":\"DuongTVTemPlaza\",\"copyright\":\"Copyright (C) 2015 TemPlaza. All rights reserved.\",\"authorEmail\":\"support@templaza.com\",\"authorUrl\":\"www.templaza.com\\/\",\"version\":\"1.0.7\",\"description\":\"PLG_EXTRAFIELDS_CHECKBOXES_XML_DESCRIPTION\",\"group\":\"\",\"filename\":\"checkboxes\"}', '{\"number_columns\":\"0\"}', 0, '0000-00-00 00:00:00', 1, 1, 0);
INSERT INTO `qk7ce_tz_portfolio_plus_extensions` VALUES(7, 'plg_extrafields_dropdownlist', 'tz_portfolio_plus-plugin', 'dropdownlist', 'extrafields', 1, '{\"name\":\"plg_extrafields_dropdownlist\",\"type\":\"tz_portfolio_plus-plugin\",\"creationDate\":\"October 20th 2015\",\"author\":\"DuongTVTemPlaza\",\"copyright\":\"Copyright (C) 2015 TemPlaza. All rights reserved.\",\"authorEmail\":\"support@templaza.com\",\"authorUrl\":\"www.templaza.com\\/\",\"version\":\"1.0.7\",\"description\":\"PLG_EXTRAFIELDS_DROPDOWNLIST_XML_DESCRIPTION\",\"group\":\"\",\"filename\":\"dropdownlist\"}', '{\"size\":\"5\"}', 0, '0000-00-00 00:00:00', 1, 1, 0);
INSERT INTO `qk7ce_tz_portfolio_plus_extensions` VALUES(8, 'plg_extrafields_multipleselect', 'tz_portfolio_plus-plugin', 'multipleselect', 'extrafields', 1, '{\"name\":\"plg_extrafields_multipleselect\",\"type\":\"tz_portfolio_plus-plugin\",\"creationDate\":\"October 20th 2015\",\"author\":\"DuongTVTemPlaza\",\"copyright\":\"Copyright (C) 2015 TemPlaza. All rights reserved.\",\"authorEmail\":\"support@templaza.com\",\"authorUrl\":\"www.templaza.com\\/\",\"version\":\"1.0.7\",\"description\":\"PLG_EXTRAFIELDS_MULTIPLESELECT_XML_DESCRIPTION\",\"group\":\"\",\"filename\":\"multipleselect\"}', '{\"size\":\"5\"}', 0, '0000-00-00 00:00:00', 1, 1, 0);
INSERT INTO `qk7ce_tz_portfolio_plus_extensions` VALUES(9, 'plg_extrafields_radio', 'tz_portfolio_plus-plugin', 'radio', 'extrafields', 1, '{\"name\":\"plg_extrafields_radio\",\"type\":\"tz_portfolio_plus-plugin\",\"creationDate\":\"October 20th 2015\",\"author\":\"DuongTVTemPlaza\",\"copyright\":\"Copyright (C) 2015 TemPlaza. All rights reserved.\",\"authorEmail\":\"support@templaza.com\",\"authorUrl\":\"www.templaza.com\\/\",\"version\":\"1.0.7\",\"description\":\"PLG_EXTRAFIELDS_RADIO_XML_DESCRIPTION\",\"group\":\"\",\"filename\":\"radio\"}', '{\"bootstrap_style\":\"1\",\"number_columns\":\"0\"}', 0, '0000-00-00 00:00:00', 1, 1, 0);
INSERT INTO `qk7ce_tz_portfolio_plus_extensions` VALUES(10, 'plg_user_profile', 'tz_portfolio_plus-plugin', 'profile', 'user', 1, '{\"name\":\"plg_user_profile\",\"type\":\"tz_portfolio_plus-plugin\",\"creationDate\":\"December 13th 2015\",\"author\":\"DuongTVTemPlaza\",\"copyright\":\"Copyright (C) 2015 TemPlaza. All rights reserved.\",\"authorEmail\":\"support@templaza.com\",\"authorUrl\":\"www.templaza.com\\/\",\"version\":\"1.0.7\",\"description\":\"PLG_USER_PROFILE_XML_DESCRIPTION\",\"group\":\"\",\"filename\":\"profile\"}', '{}', 0, '0000-00-00 00:00:00', 1, 1, 0);
INSERT INTO `qk7ce_tz_portfolio_plus_extensions` VALUES(11, 'elegant', 'tz_portfolio_plus-template', 'elegant', '', 0, '{\"name\":\"elegant\",\"type\":\"tz_portfolio_plus-template\",\"creationDate\":\"August 17th 2017\",\"author\":\"Sonny\",\"copyright\":\"Copyright (C) 2017 TemPlaza. All rights reserved.\",\"authorEmail\":\"sonlv@templaza.com\",\"authorUrl\":\"www.templaza.com\",\"version\":\"1.0\",\"description\":\"TZ_PORTFOLIO_PLUS_TPL_XML_DESCRIPTION\",\"group\":\"\",\"filename\":\"template\"}', '{\"use_single_layout_builder\":\"0\",\"load_style\":\"1\"}', 0, '0000-00-00 00:00:00', 1, 1, 0);
