
DROP TABLE IF EXISTS `qk7ce_komento_acl`;
CREATE TABLE `qk7ce_komento_acl` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `cid` varchar(255) NOT NULL,
  `component` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `rules` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `qk7ce_komento_acl` VALUES(1, '1', 'com_content', 'usergroup', '{\"read_comment\":true,\"read_stickies\":true,\"read_lovies\":true,\"add_comment\":true,\"like_comment\":false,\"report_comment\":false,\"share_comment\":true,\"reply_comment\":false,\"upload_attachment\":false,\"download_attachment\":true,\"edit_own_comment\":false,\"delete_own_comment\":false,\"delete_own_attachment\":false,\"author_edit_comment\":false,\"author_delete_comment\":false,\"author_publish_comment\":false,\"author_unpublish_comment\":false,\"author_stick_comment\":false,\"author_delete_attachment\":false,\"edit_all_comment\":false,\"delete_all_comment\":false,\"publish_all_comment\":false,\"unpublish_all_comment\":false,\"stick_all_comment\":false,\"delete_all_attachment\":false,\"read_others_comment\":true}');
INSERT INTO `qk7ce_komento_acl` VALUES(2, '9', 'com_content', 'usergroup', '{\"read_comment\":true,\"read_stickies\":true,\"read_lovies\":true,\"add_comment\":true,\"like_comment\":false,\"report_comment\":false,\"share_comment\":true,\"reply_comment\":false,\"upload_attachment\":false,\"download_attachment\":true,\"edit_own_comment\":false,\"delete_own_comment\":false,\"delete_own_attachment\":false,\"author_edit_comment\":false,\"author_delete_comment\":false,\"author_publish_comment\":false,\"author_unpublish_comment\":false,\"author_stick_comment\":false,\"author_delete_attachment\":false,\"edit_all_comment\":false,\"delete_all_comment\":false,\"publish_all_comment\":false,\"unpublish_all_comment\":false,\"stick_all_comment\":false,\"delete_all_attachment\":false,\"read_others_comment\":true}');
INSERT INTO `qk7ce_komento_acl` VALUES(3, '2', 'com_content', 'usergroup', '{\"read_comment\":true,\"read_stickies\":true,\"read_lovies\":true,\"add_comment\":true,\"like_comment\":true,\"report_comment\":true,\"share_comment\":true,\"reply_comment\":true,\"upload_attachment\":true,\"download_attachment\":true,\"edit_own_comment\":false,\"delete_own_comment\":false,\"delete_own_attachment\":false,\"author_edit_comment\":false,\"author_delete_comment\":false,\"author_publish_comment\":false,\"author_unpublish_comment\":false,\"author_stick_comment\":false,\"author_delete_attachment\":false,\"edit_all_comment\":false,\"delete_all_comment\":false,\"publish_all_comment\":false,\"unpublish_all_comment\":false,\"stick_all_comment\":false,\"delete_all_attachment\":false,\"read_others_comment\":true}');
INSERT INTO `qk7ce_komento_acl` VALUES(4, '6', 'com_content', 'usergroup', '{\"read_comment\":true,\"read_stickies\":true,\"read_lovies\":true,\"add_comment\":true,\"like_comment\":true,\"report_comment\":true,\"share_comment\":true,\"reply_comment\":true,\"upload_attachment\":true,\"download_attachment\":true,\"edit_own_comment\":true,\"delete_own_comment\":true,\"delete_own_attachment\":true,\"author_edit_comment\":false,\"author_delete_comment\":false,\"author_publish_comment\":false,\"author_unpublish_comment\":false,\"author_stick_comment\":false,\"author_delete_attachment\":false,\"edit_all_comment\":false,\"delete_all_comment\":false,\"publish_all_comment\":false,\"unpublish_all_comment\":false,\"stick_all_comment\":false,\"delete_all_attachment\":false,\"read_others_comment\":true}');
INSERT INTO `qk7ce_komento_acl` VALUES(5, '7', 'com_content', 'usergroup', '{\"read_comment\":true,\"read_stickies\":true,\"read_lovies\":true,\"add_comment\":true,\"like_comment\":true,\"report_comment\":true,\"share_comment\":true,\"reply_comment\":true,\"upload_attachment\":true,\"download_attachment\":true,\"edit_own_comment\":true,\"delete_own_comment\":true,\"delete_own_attachment\":true,\"author_edit_comment\":false,\"author_delete_comment\":false,\"author_publish_comment\":false,\"author_unpublish_comment\":false,\"author_stick_comment\":false,\"author_delete_attachment\":false,\"edit_all_comment\":true,\"delete_all_comment\":true,\"publish_all_comment\":true,\"unpublish_all_comment\":true,\"stick_all_comment\":true,\"delete_all_attachment\":true,\"read_others_comment\":true}');
INSERT INTO `qk7ce_komento_acl` VALUES(6, '3', 'com_content', 'usergroup', '{\"read_comment\":true,\"read_stickies\":true,\"read_lovies\":true,\"add_comment\":true,\"like_comment\":true,\"report_comment\":true,\"share_comment\":true,\"reply_comment\":true,\"upload_attachment\":true,\"download_attachment\":true,\"edit_own_comment\":true,\"delete_own_comment\":false,\"delete_own_attachment\":false,\"author_edit_comment\":true,\"author_delete_comment\":true,\"author_publish_comment\":true,\"author_unpublish_comment\":true,\"author_stick_comment\":true,\"author_delete_attachment\":true,\"edit_all_comment\":false,\"delete_all_comment\":false,\"publish_all_comment\":false,\"unpublish_all_comment\":false,\"stick_all_comment\":false,\"delete_all_attachment\":false,\"read_others_comment\":true}');
INSERT INTO `qk7ce_komento_acl` VALUES(7, '4', 'com_content', 'usergroup', '{\"read_comment\":true,\"read_stickies\":true,\"read_lovies\":true,\"add_comment\":true,\"like_comment\":true,\"report_comment\":true,\"share_comment\":true,\"reply_comment\":true,\"upload_attachment\":true,\"download_attachment\":true,\"edit_own_comment\":true,\"delete_own_comment\":false,\"delete_own_attachment\":false,\"author_edit_comment\":true,\"author_delete_comment\":true,\"author_publish_comment\":true,\"author_unpublish_comment\":true,\"author_stick_comment\":true,\"author_delete_attachment\":true,\"edit_all_comment\":false,\"delete_all_comment\":false,\"publish_all_comment\":false,\"unpublish_all_comment\":false,\"stick_all_comment\":false,\"delete_all_attachment\":false,\"read_others_comment\":true}');
INSERT INTO `qk7ce_komento_acl` VALUES(8, '5', 'com_content', 'usergroup', '{\"read_comment\":true,\"read_stickies\":true,\"read_lovies\":true,\"add_comment\":true,\"like_comment\":true,\"report_comment\":true,\"share_comment\":true,\"reply_comment\":true,\"upload_attachment\":true,\"download_attachment\":true,\"edit_own_comment\":true,\"delete_own_comment\":false,\"delete_own_attachment\":false,\"author_edit_comment\":true,\"author_delete_comment\":true,\"author_publish_comment\":true,\"author_unpublish_comment\":true,\"author_stick_comment\":true,\"author_delete_attachment\":true,\"edit_all_comment\":false,\"delete_all_comment\":false,\"publish_all_comment\":true,\"unpublish_all_comment\":true,\"stick_all_comment\":true,\"delete_all_attachment\":false,\"read_others_comment\":true}');
INSERT INTO `qk7ce_komento_acl` VALUES(9, '8', 'com_content', 'usergroup', '{\"read_comment\":true,\"read_stickies\":true,\"read_lovies\":true,\"add_comment\":true,\"like_comment\":true,\"report_comment\":true,\"share_comment\":true,\"reply_comment\":true,\"upload_attachment\":true,\"download_attachment\":true,\"edit_own_comment\":true,\"delete_own_comment\":true,\"delete_own_attachment\":true,\"author_edit_comment\":true,\"author_delete_comment\":true,\"author_publish_comment\":true,\"author_unpublish_comment\":true,\"author_stick_comment\":true,\"author_delete_attachment\":true,\"edit_all_comment\":true,\"delete_all_comment\":true,\"publish_all_comment\":true,\"unpublish_all_comment\":true,\"stick_all_comment\":true,\"delete_all_attachment\":true,\"read_others_comment\":true}');
