<?php
/**
* @copyright	Copyright (C) 2008-2009 CMSJunkie. All rights reserved.
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// No direct access
defined( '_JEXEC' ) or die( 'Restricted access' );

class JHotelReservationControllerViewedProperties extends JControllerLegacy
{
	/**
	 * constructor (registers additional tasks to methods)
	 * @return void
	 */
	function __construct()
	{
		parent::__construct();
	}

	function display( $cachable = false, $urlparams = array() ) {
		return parent::display( $cachable, $urlparams ); // TODO: Change the autogenerated stub
	}

	//api to save the comment
    public function saveRecentViewedProperties(){
        //call model methods
        $model = $this->getModel('viewedproperties');
	    $post = JRequest::get( 'post' );
        $model->saveRecentViewedProperties($post);
    }

    //api to delete a comment only by the user who made it
    public function deleteProperty(){
        //call model methods
	    $propertyId = JRequest::getVar('propertyId');

        $model = $this->getModel('viewedproperties');
        $model->deleteProperty($propertyId);
    }

    //api to delete a comment only by the user who made it
	public function deleteProperties(){
		//call model methods
		$model = $this->getModel('viewedproperties');
		$model->deleteProperties();
	}

    //login the user to comment
    public function checkUser() {
	    $link = JURI::current();
        UserService::isUserLoggedIn($link);
    }
}